export const ERROR_MESSAGE = "FLYING POLAR BUFFALO ERROR";

export const HTTP_NOT_AUTHORIZED = 402

/**
 * @link https://tc39.es/proposal-unified-intl-numberformat/section6/locales-currencies-tz_proposed_out.html#sec-issanctionedsimpleunitidentifier
 */
export const ES_UNITS = {
  ACRE: "acre",
  BIT: "bit",
  BYTE: "byte",
  CELSIUS: "celsius",
  CENTIMETER: "centimeter",
  DAY: "day",
  DEGREE: "degree",
  fahrenheit: "fahrenheit",
  FLUID_OUNCE: "fluid-ounce",
  foot: "foot",
  gallon: "gallon",
  GIGABIT: "gigabit",
  GIGABYTE: "gigabyte",
  GRAM: "gram",
  hectare: "hectare",
  HOUR: "hour",
  INCH: "inch",
  KILOBIT: "kilobit",
  KILOBYT: "kilobyte",
  KILOGRAM: "kilogram",
  KILOMETER: "kilometer",
  LITER: "liter",
  MEGABIT: "megabit",
  MEGABYTE: "megabyte",
  METER: "meter",
  MILE: "mile",
  MILE_SCANDINAVIAN: "mile-scandinavian",
  milliliter: "milliliter",
  millimeter: "millimeter",
  millisecond: "millisecond",
  minute: "minute",
  month: "month",
  ounce: "ounce",
  percent: "percent",
  petabyte: "petabyte",
  pound: "pound",
  second: "second",
  stone: "stone",
  terabit: "terabit",
  terabyte: "terabyte",
  week: "week",
  yard: "yard",
  year: "year",
}