export type {
  ICalendarNoteInit,
  ICalendarNote,
  ICalendarNoteClient,
  IAccount,
  IAccountClient,
  IAccountInit,
  IEmailConfirmation,
  IComment,
  ICommentClient,
  ICommentInit,
  ISerialInteger,
  IAccountProfile,
  IAccountProfileClient,
  IAccountProfileInit,
} from "#codegen/schema/interfaces";
